# BACKEND 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: employee-backend
          env:
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "warn"

---

# FRONTEND PATCH
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: employee-frontend
          env:
            - name: VITE_API_URL
              value: "https://api.example.com"
            - name: MODE
              value: "production"
